# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    providers:
        gestion:
            entity:
                class: AdminBundle:User
                property: email

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
        in_memory:
            memory: ~
            
    encoders:
        AdminBundle\Entity\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: gestion
            
            form_login:
                login_path: home
                check_path: loginCheck
                default_target_path: /admin
            logout:
                path: logOut
                target: /
                
    access_control:
        - { path: ^/admin , roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
